CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201223172141_InitialCreate') THEN
    CREATE TABLE "Clients" (
        "ClientId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "FullName" text NOT NULL,
        "Address" text NULL,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201223172141_InitialCreate') THEN
    CREATE TABLE "Accounts" (
        "AccountId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountNumber" text NOT NULL,
        "CurrencyName" text NOT NULL,
        "Balance" numeric NOT NULL,
        "OpeningDate" timestamp without time zone NOT NULL DEFAULT (now()),
        "Status" text NOT NULL,
        "ClientId" integer NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("AccountId"),
        CONSTRAINT "FK_Accounts_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201223172141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Accounts_AccountNumber" ON "Accounts" ("AccountNumber");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201223172141_InitialCreate') THEN
    CREATE INDEX "IX_Accounts_ClientId" ON "Accounts" ("ClientId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201223172141_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201223172141_InitialCreate', '5.0.1');
    END IF;
END $$;
COMMIT;
